// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVD2HX1sVRoyvIPT-JXM646GGr5PRLwq0',
    appId: '1:901358764373:android:a196d488b85dc3aa5dafdc',
    messagingSenderId: '901358764373',
    projectId: 'taxipro-usuariox',
    storageBucket: 'taxipro-usuariox.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiY9u0DjS_I-JeDc9AY2HK1MFRozU0JX4',
    appId: '1:901358764373:ios:d15e9cef6591de4c5dafdc',
    messagingSenderId: '901358764373',
    projectId: 'taxipro-usuariox',
    storageBucket: 'taxipro-usuariox.firebasestorage.app',
    androidClientId: '901358764373-2km8353ca0ahh9s1rbfq684ui57lc7bb.apps.googleusercontent.com',
    iosClientId: '901358764373-cuk4gv6q3fbpvphv32602shqlotdc182.apps.googleusercontent.com',
    iosBundleId: 'com.taxipro.taxiproUsuariox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiY9u0DjS_I-JeDc9AY2HK1MFRozU0JX4',
    appId: '1:901358764373:ios:d15e9cef6591de4c5dafdc',
    messagingSenderId: '901358764373',
    projectId: 'taxipro-usuariox',
    storageBucket: 'taxipro-usuariox.firebasestorage.app',
    androidClientId: '901358764373-2km8353ca0ahh9s1rbfq684ui57lc7bb.apps.googleusercontent.com',
    iosClientId: '901358764373-cuk4gv6q3fbpvphv32602shqlotdc182.apps.googleusercontent.com',
    iosBundleId: 'com.taxipro.taxiproUsuariox',
  );
}
