// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVnpGERWs82_o__51-BwK7YiFld9e7tXQ',
    appId: '1:569260142078:android:1c847f5d602da765fba4af',
    messagingSenderId: '569260142078',
    projectId: 'taxipro-chofer',
    storageBucket: 'taxipro-chofer.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiY9u0DjS_I-JeDc9AY2HK1MFRozU0JX4',
    appId: '1:569260142078:ios:placeholder',
    messagingSenderId: '569260142078',
    projectId: 'taxipro-chofer',
    storageBucket: 'taxipro-chofer.firebasestorage.app',
    androidClientId: '569260142078-placeholder.apps.googleusercontent.com',
    iosClientId: '569260142078-placeholder.apps.googleusercontent.com',
    iosBundleId: 'com.taxipro.usuariox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiY9u0DjS_I-JeDc9AY2HK1MFRozU0JX4',
    appId: '1:569260142078:ios:placeholder',
    messagingSenderId: '569260142078',
    projectId: 'taxipro-chofer',
    storageBucket: 'taxipro-chofer.firebasestorage.app',
    androidClientId: '569260142078-placeholder.apps.googleusercontent.com',
    iosClientId: '569260142078-placeholder.apps.googleusercontent.com',
    iosBundleId: 'com.taxipro.usuariox',
  );
}